# Generated by Django 5.1 on 2024-09-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Friend', 'verbose_name_plural': 'Friend'},
        ),
    ]
