# Generated by Django 5.1 on 2024-09-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_friend_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friendName',
            new_name='friend',
        ),
    ]
