# Generated by Django 5.1 on 2024-09-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_friendname_friend_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='talkDate',
            field=models.DateTimeField(auto_now=True, verbose_name='会話日時'),
        ),
    ]
