# Generated by Django 5.1 on 2024-09-14 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_friend_friend_remove_friend_registrationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(through='myapp.Friendship', to=settings.AUTH_USER_MODEL, verbose_name='友達'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
