# Generated by Django 5.1 on 2024-09-14 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_friendship_friend_customuser_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('talkDate', models.DateTimeField(auto_now=True, verbose_name='会話日時')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to=settings.AUTH_USER_MODEL, verbose_name='友達')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Frienduser', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friend',
            },
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
