# Generated by Django 5.1 on 2024-09-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_friend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='メッセージ'),
        ),
    ]
