# Generated by Django 5.1 on 2024-09-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_friend_pair'),
        ),
    ]
