# Generated by Django 5.1 on 2024-09-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_friend_unique_friend_pair_alter_friend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
    ]
