# Generated by Django 5.1 on 2024-09-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_friend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
