# Generated by Django 5.1 on 2024-09-23 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='message',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='talkDate',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.CreateModel(
            name='TalkRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talkDate', models.DateTimeField(auto_now=True, verbose_name='会話日時')),
                ('message', models.TextField(blank=True, null=True, verbose_name='メッセージ')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
