# Generated by Django 5.1 on 2024-09-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_friend_message_remove_friend_talkdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkroom',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='myapp.friend'),
        ),
    ]
