# Generated by Django 5.1 on 2024-10-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
