# Generated by Django 5.1 on 2024-10-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_customuser_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
